[workspace]
members = ["plonky2x/core", "plonky2x/derive", "rustx", "api"]
resolver = "2"

[profile.release]
opt-level = 3
incremental = true
#lto = "fat"
#codegen-units = 1

[profile.bench]
opt-level = 3
