[package]
name = "succinctx-client"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.4.2", features = ["serde"] }
anyhow = "1.0.75"
ethers = "2.0.10"
log = "0.4.20"
reqwest = "0.11.22"
serde = "1.0.192"
serde_json = "1.0.108"
